from .simulation_based.celf import CELF
from .simulation_based.celfpp import CELF_PP
from .simulation_based.mcgreedy import MCGreedy
from .simulation_based.cga import CGA
from .simulation_based.cgina import CGINA
from .proxy_based.degdis import DegDis
from .proxy_based.highest_out_degree import HighestOutDegree
from .proxy_based.simpath import SimPath
from .proxy_based.group_pr import Group_PR